name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # الحصول على التاريخ
      - name: Get Date
        id: get-date
        run: echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_ENV

      # تخزين الدليل العالمي لـ Buildozer
      - name: Cache Buildozer global directory
        uses: actions/cache@v3  # تحديث إلى الإصدار الجديد
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # تخزين دليل Buildozer
      - name: Cache Buildozer directory
        uses: actions/cache@v3  # تحديث إلى الإصدار الجديد
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.date }}-${{ hashFiles('buildozer.spec') }}

          # قائمة الملفات للتحقق من وجود buildozer.spec
      - name: List files
        run: ls -R

      # البناء باستخدام Buildozer
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      # رفع النتائج كـ artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./bin/*  # تأكد من أن هذا المسار هو المكان الذي يتم فيه تخزين ملفات APK
